# Generated by Django 5.0.7 on 2024-07-15 16:34

import customUser.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customUser", "0002_customuser_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=customUser.models.user_directory_path
            ),
        ),
    ]
