name: FinalProjectBackend2
dependencies:
    - python
    - pip
    - pip:
      - django
      - djangorestframework
      - djangorestframework-simplejwt
      - drf-yasg
      - django-dotenv
      - django-storages   # Used to connect to deployed media files storage
      - django-cors-headers  # Used to allow connection between frontend to backend
      - dj-database-url   # Used to configure Postgres via Heroku URL
      - gunicorn         # Python web server to run application
      - markdown           # Used by drf-yasg for automatic api documentation
      - pillow             # Python image library - needed when handling images
      - whitenoise         # Library to serve static files in deployment mode
      - boto3           # AWS SDK - allows application to interact with things like AWS S3 or DO Spaces
      - psycopg2-binary