# Generated by Django 5.0.6 on 2024-07-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AbsenceRequest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("startDt", models.DateTimeField()),
                ("endDt", models.DateTimeField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("vacation", "Vacation"),
                            ("sick_leave", "Sick Leave"),
                        ],
                        default="vacation",
                        max_length=11,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=11,
                    ),
                ),
                ("dtCreated", models.DateTimeField(auto_now_add=True)),
                ("dtUpdated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
