# Generated by Django 5.0.6 on 2024-07-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='absenceRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('startDt', models.DateTimeField()),
                ('endDt', models.DateTimeField()),
                ('reason', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=300)),
                ('dtCreated', models.DateTimeField(auto_now_add=True)),
                ('dtUpdated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
