# Generated by Django 5.0.6 on 2024-07-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absenceRequests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absencerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=11),
        ),
    ]
