# Generated by Django 5.0.6 on 2024-07-04 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absenceRequests', '0002_alter_absencerequest_status'),
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='absencerequest',
            name='requesterId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='absenceRequest', to='userProfile.userprofile'),
        ),
    ]
