# Generated by Django 5.0.7 on 2024-07-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("absenceRequests", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="absencerequest",
            name="durationWorkHours",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="absencerequest",
            name="durationWorkTimeFormatted",
            field=models.CharField(default=-1),
            preserve_default=False,
        ),
    ]
