# Generated by Django 5.0.7 on 2024-07-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("absenceRequests", "0003_absencerequest_durationworkhours_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="absencerequest",
            name="durationWorkHours",
            field=models.FloatField(default=-1.0),
        ),
        migrations.AlterField(
            model_name="absencerequest",
            name="durationWorkTimeFormatted",
            field=models.CharField(default="-1d_-1h_-1m"),
        ),
    ]
