# Generated by Django 5.0.6 on 2024-07-04 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absenceRequests', '0003_absencerequest_requesterid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='absencerequest',
            old_name='requesterId',
            new_name='requester',
        ),
    ]
