# Generated by Django 5.0.6 on 2024-07-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absenceRequests', '0004_rename_requesterid_absencerequest_requester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absencerequest',
            name='reason',
            field=models.CharField(choices=[('vacation', 'Vacation'), ('sick_leave', 'Sick Leave')], default='vacation', max_length=11),
        ),
    ]
