# Generated by Django 5.0.6 on 2024-07-08 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absenceRequests', '0005_alter_absencerequest_reason'),
        ('userProfile', '0007_alter_userprofile_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absencerequest',
            name='requester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='absenceRequest_related', to='userProfile.userprofile'),
        ),
    ]
