# Generated by Django 5.0.6 on 2024-07-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompaniesProfile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("companyName", models.CharField(max_length=100)),
            ],
        ),
    ]
