# Generated by Django 5.0.6 on 2024-07-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeDependentVar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('variable', models.CharField(choices=[('nr_tot_vacation_days', 'Total Vacation Days'), ('pensum_perc', 'Pensum %'), ('maternity_leave', 'Maternity Leave'), ('nr_working_hours_per_week', 'Working Hours per Week')], default='nr_tot_vacation_days', max_length=25)),
                ('value', models.FloatField()),
            ],
        ),
    ]
