# Generated by Django 5.0.6 on 2024-07-04 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeDependentVar', '0001_initial'),
        ('userProfile', '0005_alter_userprofile_approver'),
    ]

    operations = [
        migrations.AddField(
            model_name='timedependentvar',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='timeDepVars', to='userProfile.userprofile'),
        ),
    ]
