# Generated by Django 5.0.6 on 2024-07-04 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companiesProfile', '0001_initial'),
        ('department', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('birthdayDate', models.DateField(blank=True, null=True)),
                ('firstDayAtWork', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='pending', max_length=11)),
                ('isCompanyAdmin', models.BooleanField(default=False)),
                ('companyId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='companiesProfile.companiesprofile')),
                ('customUserId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('departmentId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='department.department')),
            ],
        ),
    ]
