# Generated by Django 5.0.7 on 2024-07-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userProfile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="canton",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="city",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="postcode",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="street",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
