# Generated by Django 5.0.6 on 2024-07-04 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_userprofile_approverid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='approverId',
            new_name='approver',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='companyId',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='customUserId',
            new_name='customUser',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='departmentId',
            new_name='department',
        ),
    ]
