# Generated by Django 5.0.6 on 2024-07-04 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_rename_approverid_userprofile_approver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='approver',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teamMember', to='userProfile.userprofile'),
        ),
    ]
