# Generated by Django 5.0.7 on 2024-07-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trainingRequests", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingrequest",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
